ClusterName=pi_cluster
SlurmctldHost=isaac
SlurmUser=slurm
SlurmdUser=root
AuthType=auth/munge
CryptoType=crypto/munge
SlurmctldPort=6817
SlurmdPort=6818
StateSaveLocation=/var/lib/slurmctld
SlurmdSpoolDir=/var/lib/slurmd
ProctrackType=proctrack/linuxproc
TaskPlugin=task/none
SelectType=select/cons_tres
SelectTypeParameters=CR_Core
SchedulerType=sched/backfill
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log

# Nodes
NodeName=pi02 CPUs=4 State=UNKNOWN
NodeName=pi03 CPUs=4 State=UNKNOWN

# Partition
PartitionName=pi Nodes=pi02,pi03 Default=YES State=UP
